// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const DATABASE_URL = `mysql://${process.env.DATABASE_USERNAME}:${process.env.DATABASE_PASSWORD}@${process.env.DATABASE_HOST}:${process.env.DATABASE_PORT}/${process.env.DATABASE_NAME}`;

export default defineConfig({
  // schema : prisma가 동작할 때 참고할 스키마 파일의 위치
  schema: "prisma/schema.prisma",
  // migrations : prisma가 초기 설정 이후 스키마 변경 시 변경 작업이 저장될 위치 지정
  migrations: {
    path: "prisma/migrations",
  },
  // datasource : prisma가 DB에 접근할 때 사용하는 링크 지정
  // mysql://아이디:비밀번호@호스트/스키마명
  datasource: {
    url: DATABASE_URL,
  },
});
